### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by Looky1173**
This PR addresses #26 and an additional typo.

### CODE REVIEW

**Review by leahcimto — APPROVED** [review]

**Comment by leahcimto** [comment]
@Accio1 Good to merge

**Review by Accio1 — APPROVED** [review]
Looks good!

**Comment by Accio1** [comment]
@Looky1173 when I went to merge this, it said that your commit isn't signed. Do you know why this happened?

**Comment by Looky1173** [comment]
@Accio1 Oh, I made the pull request with GitHub Desktop so it wasn't digitally signed. Should I make a new signed PR? (I'm new to the concept of signing commits on GitHub as well...)

**Comment by Accio1** [comment]
> @Accio1 Oh, I made the pull request with GitHub Desktop so it wasn't digitally signed. Should I make a new signed PR? (I'm new to the concept of signing commits on GitHub as well...)

@Looky1173 if you wouldn't mind. It will just make it easier for me to merge.

**Comment by Looky1173** [comment]
@Accio1 Okay, #29 is finally verified!
image

**Pull request closed without merging**
