### PR TITLE
Update Responses

### PR DESCRIPTION
**Pull request by leahcimto**
This updates responses and removes things that are frowned upon and often called "mini-modding". 

I also made a licence file way back when, but I deleted it

CC: @Accio1

### CODE REVIEW

**Comment by leahcimto** [comment]
Closes #12

**Comment by leahcimto** [comment]
@Accio1 could you please review this?

**Review by Accio1 — APPROVED** [review]
I made a small change, looks good to merge!

**Comment by leahcimto** [comment]
Thanks!

**Pull request merged**
