### PR TITLE
Added a new message for the Suggestions forum

### PR DESCRIPTION
**Pull request by VFDan**

### CODE REVIEW

**Review by Accio1 — CHANGES_REQUESTED** [review]
This new addition, and the one before it both have an id of Text4, and the function attatched to them applies to (4). This will break the function because each block of text needs to have a seperate id in order for it to work correctly.

**Comment by VFDan** [comment]
Ah, I didn't notice that

**Comment by VFDan** [comment]
👍 Fixed

**Review by Accio1 — APPROVED** [review]
Looks good!

**Pull request merged**
